name: Update README stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create profile directory
        run: mkdir -p profile

      - name: Generate GitHub Stats
        run: |
          curl -o profile/stats.svg "https://github-readme-stats.vercel.app/api?username=SurajBilgi&show_icons=true&theme=tokyonight&hide_border=true"

      - name: Generate Top Languages
        run: |
          curl -o profile/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=SurajBilgi&layout=compact&theme=tokyonight&hide_border=true"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add profile/*.svg
          git commit -m "Update README stats"
          git push
